### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by royemosby** [rodrigobdz/alfred-swap-user-workflow#1]
Tested out the script included in the workflow and it gives a "no such file or directory error"

```bash
CURRENT_USER_ID="$(whoami | id -u)"
USERS="$(dscacheutil -q user | grep -e 5'[0-9][0-2'])"
USER_IDS="$(echo "$USERS" | awk '{print $2}')"
NEXT_USER_ID="$(echo "$USER_IDS" | grep -v $CURRENT_USER_ID)"

/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -switchToUserID $NEXT_USER_ID
zsh: no such file or directory: /System/Library/CoreServices/Menu Extras/User.menu/Contents/Resources/CGSession
```

System Version:	macOS 11.6 (20G165)
Kernel Version:	Darwin 20.6.0

Alfred Version: 4.6[1266]

I followed the directory structure and get up to `Menu Extras`. `User.menu` does not exist on my system.

**Comment by rodrigobdz** [comment]
@royemosby Thanks for opening this issue. Apparently, this is a common [issue](https://apple.stackexchange.com/a/409836) starting from macOS Big Sur onwards because the script was removed. At the moment, there seems to be no replacement for said script.

I mention in the [readme](https://github.com/rodrigobdz/alfred-swap-user-workflow/commit/e138b00dd414a1d7b7a192ed20fc61ecd848e947) this limitation.

**Comment by royemosby** [comment]
I found an AppleScript that gets 80% there:

```applescript
tell application "System Events"
	tell its application process "ControlCenter"
		tell its menu bar 1
			click its menu bar item "User"
		end tell
		
		tell its window "Control Center"
			tell its group 1
				set btns to its buttons
				repeat with btn in btns
					if name of btn = "Login Window..." then
						click btn
					end if
				end repeat
			end tell
		end tell
	end tell
end tell
```

The above directs to the login window.
